server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider8801 #服务名
  cloud:
    stream:
      binders: #在此处配合要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        output: #这个名字是一个通道的名字
          destination: customer8801Exchange #表示要使用的Exchange你名称定义
          content-type: application/json #设置消息类型，本次为json，文本则为"text/plain"
          binder: defaultRabbit #设置要绑定的额消息服务的具体设置
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  #actuator的设置
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔(默认30秒)
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的时间间隔(默认为90秒)
    instance-id: send-8801.com #在信息列表时显示主机名称
    prefer-ip-address: true #访问的路劲改变为IP地址
