server:
  port: 3344
spring:
  application:
    name: cloud-config-center # 注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          # git@github.com:为固定写法，后面为用户名/项目/文件信息
          uri: https://github.com/xwbGithub/springcloud-config.git #github上面的git层库名字
          #搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: master
  #RabbitMQ的配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
# rabbitmq相关配置，暴露bus刷新配置的断点
management:
  endpoints: #暴露bus刷新配置的断点
    web:
      exposure:
        include:  'bus-refresh'