server:
  port: 8002
spring:
  application:
    name: cloud-payment-service #服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前mysql的驱动类型
    driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.xwb.springcloud.entity
# eureka client配置
eureka:
  client:
    register-with-eureka: true #是否注册自己进入eureka
    fetch-registry: true #false表示我就是注册中心，我的之策就是维护服务实力，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #单机版配置
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  #集群配置
  #actuator的配置
  instance:
    instance-id: payment8002
    prefer-ip-address: true #访问路径可以显示ip地址