server:
  port: 9527 #端口号为9527
spring:
  application:
    name: cloud-gateway9527 #服务名
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
          - id:  payment_route #payment_route  路由的id，没有固定规则但要求唯一，建议配合服务名
            #uri: http://localhost:8001 #匹配后提供服务的路由地址
            #cloud-payment-service为eureka注册的服务名 lb是url的协议，表示启用Gateway的负载均衡功能
            uri: lb://cloud-payment-service #微服务提供服务的路由地址()
            predicates:
              - Path=/payment/get/**  #断言，路径相匹配的进行路由
              - After=2020-12-06T16:05:15.580+08:00[Asia/Shanghai] #在当前访问时间之后有效
              - Method=GET

          - id: payment_route2 #payment_route2  路由的id，没有固定规则但要求唯一，建议配合服务名
            #uri: http://localhost:8001 #匹配后提供服务的路由地址
            uri: lb://cloud-payment-service #匹配后提供服务的路由地址
            predicates:
              - Path=/payment/lb/**  #断言，路径相匹配的进行路由
              #- Host=**.gateway9527.com #当匹配规则为此路径的时候允许访问
eureka:
  instance:
    hostname: cloud-gateway-service #在eureka中显示的服务名称
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone:: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
