### Send POST request with json body
POST http://localhost:8001/payment/create
Content-Type: application/json

{
  "id":1,
  "serial": "测试数据"
}

### Send POST request with body as parameters
GET http://localhost:8001/payment/get/234
Content-Type: application/x-www-form-urlencoded