server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment #服务名称
# eureka client配置
eureka:
  client:
    register-with-eureka: true #是否注册自己进入eureka
    fetch-registry: true #false表示我就是注册中心，我的之策就是维护服务实力，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #单机版配置
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  #集群配置
