### Send POST request with json body
POST http://localhost:80/consumer/payment/create
Content-Type: application/json

{
  "serial": "测试数据80api端口"
}

### Send POST request with body as parameters
GET http://localhost:80/consumer/payment/get/1
Content-Type: application/x-www-form-urlencoded